### ISSUE TITLE
4.0.x doesn't give same warnings which 3.0.1 used to

### ISSUE THREAD

**Issue by Changilainen** [IDPF/epubcheck#656] opened 2015-12-02 10:22 UTC
At least these two warnings, see the attachment
![example](https://cloud.githubusercontent.com/assets/496425/11528452/6fce7a30-9919-11e5-966e-c2b9987ce354.jpg)
Same EPUB file but 3.0.1 gives these two warnings.
First one is about missing / in http://
Second one is about different unique identifier in content.opf and toc.ncx files.
I also tried in 4.0.0 and it didn't give these two warnings.

Wondering is this a bug or supposed to work like this in 4.0.x?

**Comment by mldean** [comment] 2016-03-15 13:28
I noticed a similar issue this morning. Epubcheck 3.0.1 caught some invalid IDs in my EPUB:
![301](https://cloud.githubusercontent.com/assets/13873141/13779126/ef91f86a-ea8f-11e5-958a-adfc3ac89f46.jpg)

But Epubcheck 4.0.1 didn't show me the error:
![401](https://cloud.githubusercontent.com/assets/13873141/13779153/ff74ab92-ea8f-11e5-8034-4dce4d2f2ab7.jpg)

I only noticed this when I tried to upload the file to iBooks, which kicked the file back with errors.

**Comment by tofi86** [comment] 2017-01-02 18:05
> First one is about missing / in http://

This is fixed with #731 / #708.

> Second one is about different unique identifier in content.opf and toc.ncx files.

There's another open issue for that: #669 

> Epubcheck 3.0.1 caught some invalid IDs in my EPUB:

That seems to be a feature of HTML5, not a bug. While `id="123"` or `id="test:123"` was invalid in XHTML 1.1 (EPUB 2) bot `id` values are now perfectly valid in HTML 5 (EPUB 3). So EpubCheck validation works es expected.

I'm closing this in favor of the other tickets. Feel free to reopen if you want to discuss this further on...

**Closed by tofi86** 2017-01-02 18:05 UTC

**Comment by tofi86** [comment] 2017-01-05 13:28
>>  Second one is about different unique identifier in content.opf and toc.ncx files.
> 
> There's another open issue for that: #669

This _IS_ currently reported, but only when you run EpubCheck with ReportLevel USAGE (commandline argument `--usage`):

    USAGE(NCX-001): /Users/tofi/Downloads/epubcheck-669_epub2-invalid.epub/EPUB/lorem.ncx(-1,-1): NCX identifier ('urn:uuid:550e8400-e29b-41d4-a716-4466674412314--2') does not match OPF identifier ('urn:uuid:550e8400-e29b-41d4-a716-4466674412314').

See #669 for further discussion of this.

**Comment by tofi86** [comment] 2017-10-25 21:57
This has been fixed with PullRequest #798 and will be included in the upcoming release v4.1. Please see #669 and #798 for discussion on the topic.
