### ISSUE TITLE
Renditions in fxl ePub

### ISSUE THREAD

**Issue by Yves-Apel** [IDPF/epubcheck#594] opened 2015-09-09 16:50 UTC
Hi,

with epubcheck 4.0.0, ePubs created with will receive the warning message:

WARNING (OPF-007) at "Untitled-1.epub/OEBPS/content.opf" (line 2, col 227):
   Re-declaration of reserved prefix 'rendition'.

Adobe fixed this for reflowable ePubs created with InDesign CC 2015. But the error also appears for fixed layout epub (also with CC 2015) where as I'm not sure at all if this is right within epubcheck. Looking at http://www.idpf.org/epub/fxl/#usage it seems to be allowed in fxl. Do you have in depth infos about that?

Thanks,
Yves

**Comment by rdeltour** [comment] 2015-09-09 18:43
These warning come from `rendition` being a [reserved prefix](http://www.idpf.org/epub/vocab/package/pfx/) in EPUB 3.0.1 and as such should not be re-defined explicitly in the `prefix` attribute. 

That said, as said in #585 (of which the current issue is a duplicate), I agree the explicit declaration should be allowed if it doesn't override the pre-defined URI.

**Comment by rdeltour** [comment] 2015-09-09 18:44
(I closed the issue since it's a duplicate of #585. Please comment there to follow up).

**Closed** 2015-09-09 18:44 UTC
Labels: duplicate
