### ISSUE TITLE
epub validator doesnt show any error

### ISSUE THREAD

**Issue by prabhathulasi** [IDPF/epubcheck#845] opened 2018-05-15 08:52 UTC
![err copy](https://user-images.githubusercontent.com/39266655/40046616-010c54de-584b-11e8-80e5-4cf257e02073.jpg)
can any one help me to solve this one i have tried many ways but  i cant able to validate this epub other epub files are validated perfectly i dont know why this file shows like this i doesn't shows up any error but the epub checker ends with error or warning

**Comment by tofi86** [comment] 2018-05-15 13:29
Closed as duplicate of #844

**Closed by tofi86** 2018-05-15 13:29 UTC
