### ISSUE TITLE
src/test/resources/20/expanded/valid/issue256/._DS_Store in 4.01 makes unarchive fail

### ISSUE THREAD

**Issue by rlhamil** [IDPF/epubcheck#709] opened 2016-10-03 19:18 UTC
The presence of `src/test/resources/20/expanded/valid/issue256/._DS_Store` makes extracting the tar.gz (at the very least) fail on a Mac, because it implies a corresponding DS_Store file which does not exist (the `.DS_Store` file is there, but since that's just Mac Finder (file manager) state, it really shouldn't be there either, but the proper AppleDouble file for that would have been `._.DS_Store`).

Such Mac droppings are generally not useful as part of a repository or archive, and cleaning them out would be a kindness. :-)

**Comment by tofi86** [comment] 2016-10-04 13:24
Thanks for dropping a note about it! The files are removed from the repo.

**Comment by rdeltour** [comment] 2016-10-04 13:41
Well, issue256 was precisely to test that such files are ignored in the validation process, so I think the file should be re-added ;-)

**Comment by tofi86** [comment] 2016-10-04 13:44
Oh gosh! 😰 Thanks for the review, @rdeltour!
Will revert the commit!

Seems as if we don't have tests for issue #256 because the build did not fail...

**Comment by tofi86** [comment] 2017-02-11 19:08
@rdeltour: As I had downloaded the tar.gz file while we talked about the issue today but totaly forgot to test, I just tried and in fact, the untar fails.

The tar.gz is generated by GitHub so I raised a support issue with the GitHub team:

> Dear GitHub team,
> 
> we have a bugreport at https://github.com/IDPF/epubcheck/issues/709
> saying, that the .tar.gz for a GitHub "Release" which is packaged by you for every release tag, cannot be untar-ed on Mac OS X.
> 
> And in fact, if you download the latest release of EpubCheck from https://github.com/IDPF/epubcheck/archive/v4.0.2.tar.gz on a Mac and try to untar with "tar xfv epubcheck-4.0.2.tar.gz" it fails with the following error:
> 
> 
> $ tar xfv epubcheck-4.0.2.tar.gz
> ...
> x epubcheck-4.0.2/src/tools/CompareVersions.py
> x epubcheck-4.0.2/src/tools/Dictionary.py
> tar: copyfile unpack (epubcheck-4.0.2/src/test/resources/20/expanded/valid/issue256/DS_Store) failed: No such file or directory
> 
> 
> Seems the hidden metadata file ".DS_Store" which is, in this case, part of a testcase in our unittest suite, fails to untar correctly.
> 
> Can you tell us whether this is a problem of how we committed the .DS_Store file or whether this is an issue on your side?

Let's see what they will respond... They're usually very quick...

**Comment by tofi86** [comment] 2017-02-12 23:34
> The presence of src/test/resources/20/expanded/valid/issue256/._DS_Store makes extracting the tar.gz (at the very least) fail on a Mac,

I did some tests and als GitHub Support was not able to reproduce in the way you @rlhamil describe the issue.

The error when using `tar` command on the commandline is
> tar: copyfile unpack (epubcheck-4.0.2/src/test/resources/20/expanded/valid/issue256/DS_Store) failed: No such file or directory

but the exit code is `0` anyway, so the tar command did not fail.

I also diffed the extracted directories with those expanded with another zip utility and they contain the same content.

So yes, there's an error message but extracting the archive works well.

Closing this as invalid. @rlhamil: please reopen if you think this isn't solved for you.

**Closed by tofi86** 2017-02-12 23:34 UTC
Labels: bug, waiting for feedback
