### ISSUE TITLE
About NCX check based on OPF identifier

### ISSUE THREAD

**Issue by shashikumar1** [IDPF/epubcheck#682] opened 2016-04-18 10:44 UTC
As we have noticed in current version of checker uniq identifier checks are not available based on opf.

**Comment by tofi86** [comment] 2016-04-18 17:09
Closed as duplicate of #669

**Closed** 2016-04-18 17:10 UTC
Labels: duplicate

**Comment by tofi86** [comment] 2017-01-05 13:28
This _IS_ currently reported, but only when you run EpubCheck with ReportLevel USAGE (commandline argument `--usage`):

    USAGE(NCX-001): /Users/tofi/Downloads/epubcheck-669_epub2-invalid.epub/EPUB/lorem.ncx(-1,-1): NCX identifier ('urn:uuid:550e8400-e29b-41d4-a716-4466674412314--2') does not match OPF identifier ('urn:uuid:550e8400-e29b-41d4-a716-4466674412314').

See #669 for further discussion of this.

**Comment by tofi86** [comment] 2017-10-25 21:57
This has been fixed with PullRequest #798 and will be included in the upcoming release v4.1. Please see #669 and #798 for discussion on the topic.
