### ISSUE TITLE
`java.lang.ExceptionInInitializerError` on latest release

### ISSUE THREAD

**Issue by jaseemabid** [IDPF/epubcheck#565] opened 2015-07-17 14:34 UTC
The issue is reproducible with the latest release
(epubcheck-4.0.0-alpha11-dist.zip). The last stable (epubcheck-3.0.1.zip) works
as expected

$ java -jar epubcheck.jar book.epub    

    Exception in thread "main" java.lang.ExceptionInInitializerError
    	at com.adobe.epubcheck.tool.EpubChecker.run(EpubChecker.java:251)
    	at com.adobe.epubcheck.tool.Checker.main(Checker.java:31)
    Caused by: java.util.MissingResourceException: Can't find bundle for base name com.adobe.epubcheck.util.messages, locale en_US
    	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1499)
    	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1322)
    	at java.util.ResourceBundle.getBundle(ResourceBundle.java:841)
    	at com.adobe.epubcheck.util.Messages.<clinit>(Messages.java:43)
    	... 2 more
    Caused by: java.lang.NoClassDefFoundError: com/google/common/base/Charsets
    	at com.adobe.epubcheck.util.Messages$UTF8Control.newBundle(Messages.java:109)
    	at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1436)
    	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1400)
    	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1354)
    	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1354)
    	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1296)
    	... 4 more
    Caused by: java.lang.ClassNotFoundException: com.google.common.base.Charsets
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    	... 10 more

    
$ java -version

    java version "1.7.0_51"
    OpenJDK Runtime Environment (IcedTea 2.4.6) (7u51-2.4.6-1ubuntu4)
    OpenJDK 64-Bit Server VM (build 24.51-b03, mixed mode)

**Comment by dusek** [comment] 2015-11-03 13:16
I had the same issue with 4.0.1 release (i.e. the identical `Exception`). I found out it to be caused by me copying the `epubcheck.jar` out of the unzipped release directory, without copying `lib` directory along with it. If I keep it there (i.e. alongside the `lib/` directory), I can run it without any issue. i.e.:

```
$ wget https://github.com/IDPF/epubcheck/releases/download/v4.0.1/epubcheck-4.0.1.zip
$ unzip epubcheck-4.0.1.zip
$ cd epubcheck-4.0.1/
$ java -jar epubcheck.jar /path/to/your/test.epub
Validating using EPUB version 3.0.1 rules.
No errors or warnings detected.
epubcheck completed
```

@jaseemabid Maybe your problem is solved by this?

**Comment by rdeltour** [comment] 2015-11-03 13:25
Thanks @dusek for spotting this old unanswered issue :wink: . This was also asked recently in #644.
I'm closing this issue as `invalid`. Feel free to keep posting in this thread...

**Closed** 2015-11-03 13:25 UTC
Labels: invalid
