### ISSUE TITLE
problems with ePubchecker 2.2

### ISSUE THREAD

**Issue by MerelAgnes** [IDPF/epubcheck#630] opened 2015-10-16 07:20 UTC
I make books for print and export them later as a ePub
ePub_Checker version 3.1.2 worked fine no errors, no problems,
 
but with ePub_Checker version 1.5.0 gives, with the same ePub, a lot of warnings/errors I don't understand, code HTM-002 and RSC-005.
Saying that the installed xml parser doesn't supprt xml verification (code HTM-002). and DOM003 Namespace error in depth /Meta-INF/container.xml (RSC-005)
 
I have Jave 8 update 60

I hope someone can help me to solve this problem

![schermafbeelding 2015-10-12 om 09 24 30kopie](https://cloud.githubusercontent.com/assets/15143147/10535903/12b50e2e-73e7-11e5-8822-491a8c89c94d.jpg)
![schermafbeelding 2015-10-12 om 09 25 03kopie](https://cloud.githubusercontent.com/assets/15143147/10535904/1664efee-73e7-11e5-9491-47f1f10e44b5.jpg)

**Comment by rdeltour** [comment] 2015-10-16 07:26
@MerelAgnes do you get the same errors when running EpubCheck from the command line?
@tofi86 does it ring a bell?

**Comment by MerelAgnes** [comment] 2015-10-16 07:34
I am sorry, but how do you do that?

**Comment by rdeltour** [comment] 2015-10-16 07:37
> I am sorry, but how do you do that?

see [the wiki page on how to run epubcheck](https://github.com/IDPF/epubcheck/wiki/Running)

**Comment by MerelAgnes** [comment] 2015-10-16 07:41
I have read that, but I don't understand it....

**Comment by rdeltour** [comment] 2015-10-16 07:46
@MerelAgnes would you have a sample EPUB to share? I can try to reproduce locally and see if the errors are legit

**Comment by MerelAgnes** [comment] 2015-10-16 07:53
Where can I send that to? Here can I only send PNG Gif etc. It doesn't support the epub file type.

**Comment by MerelAgnes** [comment] 2015-10-16 07:54
I,ve send one to your email...

**Comment by rdeltour** [comment] 2015-10-16 08:08
> Where can I send that to? Here can I only send PNG Gif etc. It doesn't support the epub file type.

either upload it somewhere public or email me at rdeltour at gmail.

**Comment by MerelAgnes** [comment] 2015-10-16 08:18
Did you receive it?

**Comment by rdeltour** [comment] 2015-10-16 08:20
> Did you receive it?

I just received it yes. I validates fine with the command line version, so I suspect this is a configuration or installation issue with Pagina's EPUB Checker. @tofi86 can you have a look?

**Comment by MerelAgnes** [comment] 2015-10-16 08:27
Thank you, i hope I can get some help to install the checker properly. I am not very good in this sort of things...

**Comment by MerelAgnes** [comment] 2015-10-16 14:27
I still have this configuration or installation issue with the EPUB Checker. How to solve it?

**Comment by rdeltour** [comment] 2015-10-16 14:48
> I still have this configuration or installation issue with the EPUB Checker. How to solve it?

I guess you can try to contact Tobias at Pagina  (@tofi86  here). His email at Pagina is on the [EpubChecker project page](http://www.pagina-online.de/produkte/epub-checker/).
But please not that this is freeware and as far as I know based on volunteering support, so you probably can't expect an immediate answer. @tofi86 is usually very reactive, but I know he's been busy with the Frankfurt Book Fair these days.

I'll close the issue here because it's apparently not a bug with EpubCheck. Feel free to keep using the thread here for follow-up comments.

**Closed** 2015-10-16 14:49 UTC
Labels: invalid

**Comment by tofi86** [comment] 2015-10-17 23:26
Will have a look on Monday when being back at the office from Frankfurt Book Fair...

**Comment by tofi86** [comment] 2015-10-17 23:27
@rdeltour can you forward me the example ePub file?

**Comment by rdeltour** [comment] 2015-10-18 07:12
> @rdeltour can you forward me the example ePub file?

Done!

**Comment by tofi86** [comment] 2015-10-18 20:56
I cannot reproduce the problem with latest pagina EPUB-Checker, @MerelAgnes:

![bildschirmfoto 2015-10-18 um 22 54 38](https://cloud.githubusercontent.com/assets/365118/10566577/6527457c-75eb-11e5-9f2b-7a457d6a8a9e.png)

It validates just fine in Terminal and pagina EPUB-Checker App.

**Comment by tofi86** [comment] 2015-10-18 20:59
@MerelAgnes Please open `Terminal.app` and type the following:

```
java -version
```

Then press ENTER

Then type the following:
```
/usr/libexec/java_home -V
```
Then press ENTER

Copy ALL of the content in Terminal window and post it here... Thanks!

**Comment by MerelAgnes** [comment] 2015-10-19 07:26
Good morning

Last login: Sun Oct 18 11:30:52 on console
MacMerel:~ merelvanmeurs$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
MacMerel:~ merelvanmeurs$ /usr/libexec/java_home -V
Matching Java Virtual Machines (3):
    1.8.0_60, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home
    1.6.0_65-b14-466.1, x86_64:	"Java SE 6"	/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
    1.6.0_65-b14-466.1, i386:	"Java SE 6"	/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home

/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home
MacMerel:~ merelvanmeurs$

**Comment by tofi86** [comment] 2015-10-19 08:49
Thanks @MerelAgnes. Java seems to be configured correctly.

Can you send me the original file `Met gesloten vuisten.epub` which is beeing checked on your screenshots? The one you sent to @rdeltour is another one...

**Comment by MerelAgnes** [comment] 2015-10-19 08:56
This ePub gives the same errors, but Met gesloten vuisten was 27mb...

![schermafbeelding-2015-10-19-om-10 53 10](https://cloud.githubusercontent.com/assets/15143147/10573486/0aa16cda-7650-11e5-9385-f03b9de14a80.jpg)

**Comment by tofi86** [comment] 2015-10-19 12:25
Thanks @MerelAgnes, but unfortunately I cannot reproduce with the new one either...

![unbenannt](https://cloud.githubusercontent.com/assets/365118/10577500/06f650f2-766c-11e5-8bde-02f21b3b0ebe.PNG)

I need you to do the following on the commandline:

1. Download epubcheck 4.0.0 from [here](https://github.com/IDPF/epubcheck/releases/download/v4.0.0/epubcheck-4.0.0.zip)
2. Unpack the zip file to your desktop and make sure the folder is named `epubcheck-4.0.0` and that it contains `epubcheck.jar` and other files
3. Open "Terminal.app"
4. Type the following: `java -jar ~/Desktop/epubcheck-4.0.0/epubcheck.jar`
5. make sure there is a blank space after `.jar `
6. Drag & Drop the EPUB file to the Terminal app. The full pathname should be inserted. Your commandline should look like this: `java -jar ~/Desktop/epubcheck-4.0.0/epubcheck.jar /Users/merelvanmeurs/Desktop/De\ zaak\ van\ de\ gestolen\ banaan.epub`
7. Press ENTER
8. Copy ALL of the content in Terminal window and post it here.
9. Type `echo $CLASSPATH` in the Terminal window and Press ENTER
10. Post the results here

**Comment by MerelAgnes** [comment] 2015-10-19 12:39
Last login: Mon Oct 19 14:33:55 on ttys000
MacMerel:~ merelvanmeurs$ java -jar ~/Desktop/epubcheck-4.0.0/epubcheck.jar /Users/merelvanmeurs/Desktop/De\ zaak\ van\ de\ gestolen\ banaan.epub 
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/META-INF/container.xml(2,82): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
Validating using EPUB version 2.0.1 rules.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/META-INF/container.xml(2,82): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/content.opf(2,88): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane-1.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane-2.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane-3.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane-4.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane-5.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane-6.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/toc.ncx(3,68): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
ERROR(RSC-005): ./Desktop/De zaak van de gestolen banaan.epub/META-INF/container.xml(-1,-1): Error while parsing file 'DOM003 Namespace error'.

Check finished with errors

epubcheck completed
MacMerel:~ merelvanmeurs$

**Comment by MerelAgnes** [comment] 2015-10-19 12:42
Last login: Mon Oct 19 14:40:53 on ttys000
MacMerel:~ merelvanmeurs$ java -jar ~/Desktop/epubcheck-4.0.0/epubcheck.jar /Users/merelvanmeurs/Desktop/De\ zaak\ van\ de\ gestolen\ banaan.epub 
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/META-INF/container.xml(2,82): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
Validating using EPUB version 2.0.1 rules.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/META-INF/container.xml(2,82): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/content.opf(2,88): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane-1.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane-2.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane-3.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane-4.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane-5.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane-6.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/toc.ncx(3,68): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
ERROR(RSC-005): ./Desktop/De zaak van de gestolen banaan.epub/META-INF/container.xml(-1,-1): Error while parsing file 'DOM003 Namespace error'.

Check finished with errors

epubcheck completed
MacMerel:~ merelvanmeurs$ echo $CLASSPATH

MacMerel:~ merelvanmeurs$

**Comment by MerelAgnes** [comment] 2015-10-19 12:45
Last login: Mon Oct 19 14:41:43 on ttys000
MacMerel:~ merelvanmeurs$ Last login: Mon Oct 19 14:40:53 on ttys000
MacMerel:~ merelvanmeurs$ java -jar ~/Desktop/epubcheck-4.0.0/epubcheck.jar /Users/merelvanmeurs/Desktop/De\ zaak\ van\ de\ gestolen\ banaan.epub 
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/META-INF/container.xml(2,82): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
Validating using EPUB version 2.0.1 rules.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/META-INF/container.xml(2,82): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/content.opf(2,88): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
WARNING(HTM-002)merelvanmeurs  ttys000                   Mon Oct 19 14:44   still logged in
merelvanmeurs  ttys000                   Mon Oct 19 14:41 - 14:43  (00:01)
merelvanmeurs  ttys000                   Mon Oct 19 14:40 - 14:41  (00:00)
merelvanmeurs  ttys000                   Mon Oct 19 14:39 - 14:40  (00:00)
merelvanmeurs  ttys000                   Mon Oct 19 14:39 - 14:39  (00:00)
merelvanmeurs  ttys000                   Mon Oct 19 14:35 - 14:39  (00:03)
merelvanmeurs  ttys000                   Mon Oct 19 14:33 - 14:35  (00:01)
merelvanmeurs  ttys000                   Mon Oct 19 09:33 - 09:33  (00:00)
merelvanmeurs  ttys000                   Mon Oct 19 09:25 - 09:27  (00:01)
merelvanmeurs  ttys000                   Fri Oct 16 16:24 - 16:29  (00:05)
merelvanmeurs  ttys000                   Fri Oct 16 16:22 - 16:24  (00:01)
merelvanmeurs  ttys000                   Fri Oct 16 16:18 - 16:22  (00:04)
merelvanmeurs  ttys000                   Fri Oct 16 15:54 - 15:54  (00:00)
merelvanmeurs  ttys000                   Fri Oct 16 15:39 - 15:47  (00:08)
merelvanmeurs  ttys000                   Thu Oct 15 13:10 - 13:12  (00:01)

wtmp begins Wed Dec 24 14:58 
MacMerel:~ merelvanmeurs$ MacMerel:~ merelvanmeurs$ java -jar ~/Desktop/epubcheck-4.0.0/epubcheck.jar /Users/merelvanmeurs/Desktop/De\ zaak\ van\ de\ gestolen\ banaan.epub 
-bash: MacMerel:~: command not found
MacMerel:~ merelvanmeurs$ WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/META-INF/container.xml(2,82): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
-bash: syntax error near unexpected token `HTM-002'
MacMerel:~ merelvanmeurs$ Validating using EPUB version 2.0.1 rules.
-bash: Validating: command not found
MacMerel:~ merelvanmeurs$ WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/META-INF/container.xml(2,82): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
-bash: syntax error near unexpected token `HTM-002'
MacMerel:~ merelvanmeurs$ WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/content.opf(2,88): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
-bash: syntax error near unexpected token `HTM-002'
MacMerel:~ merelvanmeurs$ WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
-bash: syntax error near unexpected token `HTM-002'
MacMerel:~ merelvanmeurs$ WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane-1.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
-bash: syntax error near unexpected token `HTM-002'
MacMerel:~ merelvanmeurs$ WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane-2.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
-bash: syntax error near unexpected token `HTM-002'
MacMerel:~ merelvanmeurs$ WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane-3.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
-bash: syntax error near unexpected token `HTM-002'
MacMerel:~ merelvanmeurs$ WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane-4.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
-bash: syntax error near unexpected token `HTM-002'
MacMerel:~ merelvanmeurs$ WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane-5.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
-bash: syntax error near unexpected token `HTM-002'
MacMerel:~ merelvanmeurs$ WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/Banaane-6.xhtml(3,44): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
-bash: syntax error near unexpected token `HTM-002'
MacMerel:~ merelvanmeurs$ WARNING(HTM-002): ./Desktop/De zaak van de gestolen banaan.epub/OEBPS/toc.ncx(3,68): The installed xml parser doesn't support xml version verification. Xml files must be a valid XML 1.0 document.
-bash: syntax error near unexpected token `HTM-002'
MacMerel:~ merelvanmeurs$ ERROR(RSC-005): ./Desktop/De zaak van de gestolen banaan.epub/META-INF/container.xml(-1,-1): Error while parsing file 'DOM003 Namespace error'.
-bash: syntax error near unexpected token `RSC-005'

**Comment by tofi86** [comment] 2015-10-19 13:12
Thanks @MerelAgnes 
So this is also happening on your console.

@rdeltour any ideas why this can happen when `$CLASSPATH` is empty?

**Comment by MerelAgnes** [comment] 2015-10-20 08:42
Good Morning,
 
I installed the Checker on the computer of my colleague and it works fine.
Very frustrating.

I hope someone finds the solution...

But for now I have a question about the warning HTM-016, can you tell me how to solve that?
I can open everything in TextWrangler...

Many thanks!

**Comment by MerelAgnes** [comment] 2015-10-20 12:22
I work in InDesign CC 2015, that generated this warning.
When I open it in Indesign CS6 there is no problem...

**Comment by tofi86** [comment] 2015-10-20 14:19
> But for now I have a question about the warning HTM-016, can you tell me how to solve that?
> I can open everything in TextWrangler...

see #631 and please avoid duplicating issues!

> I installed the Checker on the computer of my colleague and it works fine.
> Very frustrating.

At the moment this seems to be an issue with your Mac so we can't investigate further more...
Still waiting for a response from Romain, though...

@rdeltour As this is also happening with epubcheck on the commandline, do you any idea how this can happen with no other libs in `$CLASSPATH`?
