### ISSUE TITLE
Missing fallback doesn't result in error in Epubcheck 4.0.0-alpha11

### ISSUE THREAD

**Issue by bitsgalore** [IDPF/epubcheck#541] opened 2015-06-09 15:37 UTC
This is related to (old) [issue 271](https://github.com/IDPF/epubcheck/issues/271), but not quite the same (I think).

The link below points to an epub 2 file that uses an Adobe Page Template:

[epub20_xpgt.epub](https://github.com/KBNLresearch/epubPolicyTests/blob/master/build/epub20_xpgt.epub)

Here's the OPF:

https://github.com/KBNLresearch/epubPolicyTests/blob/master/content/epub20_xpgt/OEBPS/content.opf

I had a look at the epub 2 spec, where I found this on Out-Of-Line XML Islands (which I think is what these Adobe Page Templates are):

<http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.3.1.2>

This says:

>  The namespace of an Out-Of-Line XML Island item must be specified with the required-namespace attribute and its fallback must be identified with either a `fallback` attribute pointing to another item or by providing CSS styling that can be used to render the island via the `fallback-style` attribute. 

Since the file contains neither of the above fallback mechanisms, I would expect this to result in a validation error. Nevertheless the [output of the 4.0.0-alpha1 version](https://github.com/KBNLresearch/epubPolicyTests/blob/master/epubcheckout/4.0.0-alpha11/epub20_xpgt.xml) only reports a warning.  

Or perhaps I'm just mis-interpreting the standard on this?

(As expected [epubcheck 3.0.1 does report an error](https://github.com/KBNLresearch/epubPolicyTests/blob/master/epubcheckout/3.0.1/epub20_xpgt.xml), which looks like the correct behaviour to me)

**Comment by rdeltour** [comment] 2015-06-16 14:42
In my understanding,  only XML documents that intend to be **directly rendered** (i.e. those that contain actual content) are considered out-of-line XML islands. Adobe Page Templates are however mere _stylesheets_, so would not require a fallback.

I'm therefore closing the issue as invalid.

@mattgarrish @mgylling can you please confirm?

**Comment by jstallent** [comment] 2015-06-16 15:29
I thought the issue is that XPGT is not a [core media type](http://www.idpf.org/epub/301/spec/epub-publications.html#sec-core-media-types)?

**Comment by rdeltour** [comment] 2015-06-16 15:53
@jstallent Yes, XPGT is definitely not a Core Media Type. The question is then whether a fallback is required or not...

**Comment by bitsgalore** [comment] 2015-06-16 16:04
Hi Romain,

Thanks for looking into this. You say that stylesheets don't require a fallback. Do you have a reference for this in the spec, because I cannot find it. (I know there is an exception for embedded fonts that are declared in the CSS, but that's something completely different).

However, have a look at the [example the spec gives here](http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.3.1.2) (you'll have to scroll down a bit) to illustrate the implementation of fallbacks - this also involves various mechanisms for conveying style info with a CSS as the ultimate fallback. This looks *really* similar to my Adobe Page Template case.

**Comment by mattgarrish** [comment] 2015-06-16 18:48
I wouldn't consider an xpgt style sheet falling into the category of an xml island, either. As noted in 3.2.1.1:

> ... a Reading System must continue down the fallback chain until it reaches a reference to an item with a media type it can display

A CSS file in the fallback chain isn't going to satisfy this requirement, so right there you have a different kind of error if you use manifest fallbacks.

But the style element already provides fallbacks of a kind, since you can list both the xpgt and any css in the document head (or import the xpgt in your css). Manifest fallbacks are for cases where no intrinsic fallback mechanism is provided, so I don't see the benefit of using them.

If the xpgt is not recognized, you'd typically want nothing to happen, not for the RS to go hunting for a css that's probably already declared.

I'd question why we report xpgt at all, unless there is no css declaration in proximity.

**Comment by jstallent** [comment] 2015-06-16 18:58
Just out of curiosity, does this come up with any other kinds of style sheets? I can't think of another file type that is used in this way. 

Also, just because there is a CSS linked in the header does not mean that that CSS is built to perform the same functions as the XPGT, so the presence of another link in the header to a CSS file does not necessarily equate to a fallback.

I think it would be best to at least warn about the use of any kind of style sheet that is not a core media type if it does not have an explicit fallback.

**Comment by rdeltour** [comment] 2015-06-16 19:21
> I'd question why we report xpgt at all, unless there is no css declaration in proximity.

I agree, and I intend to revert that as a solution to issue #271.

> just because there is a CSS linked in the header does not mean that that CSS is built to perform the same functions as the XPGT, so the presence of another link in the header to a CSS file does not necessarily equate to a fallback.
> I think it would be best to at least warn about the use of any kind of style sheet that is not a core media type if it does not have an explicit fallback.

I do not disagree with the statement that a CSS doesn't necessarily performs the same function as the XPGT. However, I believe that requiring an explicit fallback is a tad overzealous because –albeit not always the case– it is perfectly valid to use CSS as fallback and consider it an "intrinsic fallback mechanism" of XPGT stylesheets.

Doing otherwise would cause false negatives, which are –in that non-critical stylesheet context– a bit more harmful than false positives IMO.

That said, we can certainly continue to repot XPGT with no explicit fallback as USAGE-level messages.

**Comment by mattgarrish** [comment] 2015-06-16 19:24
I started typing and then up popped Romain's response so I won't repeat.

But, I wasn't intending to suggest equivalence, only that you've included the non-core one without any core around. It's not quite an intrinsic fallback mechanism, but being able to repeat style declarations is pretty close in my mind.

**Closed** 2015-08-28 22:18 UTC
Labels: invalid
