### ISSUE TITLE
ePub checker tool: attribute "sketch:type" not allowed here; 

### ISSUE THREAD

**Issue by ashutosh1290** [IDPF/epubcheck#489] opened 2014-12-04 04:27 UTC
Hi, 
I have created one ePub using svg images. In validation time Epub checker tool throwing error: 

ERROR: 80P_1413179195.220609.epub/OPS/assets/css/images/black/icon-star.svg(5,37): attribute "sketch:type" not allowed here; 

Note:SVG images are rendering fine in reader.

Please suggest how can fix this error.

Thanks,
Ashutosh

**Comment by tofi86** [comment] 2016-12-30 23:08
Closing this as duplicate of #491

**Closed by tofi86** 2016-12-30 23:08 UTC
