### ISSUE TITLE
error message repetition

### ISSUE THREAD

**Issue by mattgarrish** [IDPF/epubcheck#535] opened 2015-05-11 13:15 UTC
I had an entry for a missing file in the package document and got 10 errors for it:

Validating against EPUB version 3.0 - custom validation
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.
Validating using EPUB version 3.0 rules.
ERROR(RSC-001): annotations.epub/annotations.epub(-1,-1): File 'EPUB/xhtml/annotations-002.xhtml' is not found.

**Comment by rdeltour** [comment] 2015-08-28 22:56
I know this is old stuff, but if you have any sample to repro, that would help ;)

**Comment by mattgarrish** [comment] 2015-08-28 23:34
Still getting with the latest build. All you have to do is add a manifest entry for any non-existent file. 

I'll send you a test file separately.

**Comment by rdeltour** [comment] 2015-08-29 21:36
It seems to be a duplicate of #516.

**Closed** 2015-08-31 07:51 UTC
Labels: duplicate
