### ISSUE TITLE
Custom namespace support

### ISSUE THREAD

**Issue by jacqueslelezard** [IDPF/epubcheck#751] opened 2017-03-15 15:19 UTC
Hi,
I would like to be sure: are custom namespace authorized in epub 3.1 ?

For example can I add my namespace:
`<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" xmlns:custom="http://custom-namespace.com">`
and then use my own prefixed tags:
`<custom:menu>This is the menu</custom:menu>` ?

It doesn't seems to be supported by epubcheck but I saw epub 3.1 was supposed to support custom attributes: [reference](https://www.w3.org/Submission/epub-contentdocs/#sec-xhtml-custom-attributes)

Did I misunderstood the w3 doc or is it an epubcheck bug?

Thanks

**Comment by tofi86** [comment] 2017-03-15 15:41
Please post issues regarding the spec to this issue tracker: https://github.com/IDPF/epub-revision/

I can confirm that there are other epubcheck issues regarding the use of custom namespaces in SVG: #491 #489

**Comment by tofi86** [comment] 2017-07-04 08:30
@mattgarrish Matt, can you help out regarding the use of custom prefixed tags? Is this missing from 3.0 validation or do we need to add this for 3.1 validation?

**Comment by mattgarrish** [comment] 2017-07-04 11:50
Custom namespaced elements are not valid in either version.

Custom namespaced attributes were allowed as some vendors are using them, and namespaced attributes are a recognized extension point (hence epub:type). But this was only allowed because attributes are essentially metadata.

Custom Elements may come at some point, but the spec that defines them is still only a working draft and needs to be referenced by HTML to be valid.

**Comment by tofi86** [comment] 2017-07-04 21:21
Alright, thanks for clarifying this, Matt! Closing this issue then.

**Closed by tofi86** 2017-07-04 21:21 UTC
Labels: missing, needs review

**Comment by jacqueslelezard** [comment] 2017-07-06 17:04
Thanks for the clarification!
